-- MySQL Script generated by MySQL Workbench
-- Sun Mar 13 23:04:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyectoPEDRO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS gestionempresas;
USE gestionempresas; 
-- -----------------------------------------------------
-- Table `catalogo_global`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_global` ;

CREATE TABLE IF NOT EXISTS `catalogo_global` (
  `idcatalogo` INT NOT NULL AUTO_INCREMENT,
  `cuit` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(100) NULL,
  `localidad` VARCHAR(100) NULL,
  `codigo_postal` VARCHAR(20) NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `n_ingr_brutos` VARCHAR(45) NULL,
  `cai` VARCHAR(45) NULL,
  `condicion_iva` VARCHAR(45) NOT NULL,
  `rubro_actividad` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `tipopersona` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idcatalogo`),
  UNIQUE INDEX `idcatalogo_unico` (`idcatalogo` ASC),
  UNIQUE INDEX `cuit_cat_unico` (`cuit` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compras` ;

CREATE TABLE IF NOT EXISTS `compras` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `fecha_emision` VARCHAR(45) NOT NULL,
  `n_comprobante` VARCHAR(45) NOT NULL,
  `codigo_autorizacion_cae` VARCHAR(100) BINARY NOT NULL,
  `fecha_vencimiento_cae` VARCHAR(45) BINARY NOT NULL,
  `total` FLOAT NOT NULL,
  `subtotal1` FLOAT NOT NULL,
  `neto_gravado1` FLOAT NOT NULL,
  `tipo_retencion1` VARCHAR(60) NOT NULL,
  `iva1` FLOAT NULL,
  `bandera_iva1` INT NOT NULL,
  `neto_gravado2` FLOAT NULL,
  `subtotal2` FLOAT NULL,
  `iva2` FLOAT NULL,
  `tipo_retencion2` VARCHAR(60) NULL,
  `bandera_iva2` VARCHAR(45) NULL,
  `total_retenciones` FLOAT NOT NULL,
  `importe_exento` FLOAT NOT NULL,
  `importe_no_gravado` FLOAT NOT NULL,
  `impuestos_internos` FLOAT NULL,
  `total_parcial_final` FLOAT NULL,
  `diferencia_con_total` FLOAT NULL,
  `fecha` DATETIME NOT NULL,
  `tipo_de_comprobante` VARCHAR(60) NOT NULL,
  `tipo_de_operacion` VARCHAR(100) NOT NULL,
  `letra_comprobante` VARCHAR(45) NULL,
  `empresas_idempresa` INT NOT NULL,
  `personas_idpersona` INT NOT NULL,
  PRIMARY KEY (`idcompra`, `empresas_idempresa`, `personas_idpersona`),
  UNIQUE INDEX `idcompras` (`idcompra`),
  UNIQUE INDEX `compras` (`idcompra`, `empresas_idempresa`, `personas_idpersona` ASC),
  INDEX `fk_compras_empresas1_idx` (`empresas_idempresa` ASC) VISIBLE,
  INDEX `fk_compras_personas1_idx` (`personas_idpersona` ASC) VISIBLE,
  CONSTRAINT `fk_compras_empresas1`
    FOREIGN KEY (`empresas_idempresa`)
    REFERENCES `empresas` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_personas1`
    FOREIGN KEY (`personas_idpersona`)
    REFERENCES `personas` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresas` ;

CREATE TABLE IF NOT EXISTS `empresas` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `cuit` VARCHAR(30) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `condicion_iva` VARCHAR(45) NOT NULL,
  `domicilio` VARCHAR(100) NOT NULL,
  `localidad` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `concepto` VARCHAR(45) NOT NULL,
  `actividad_principal` VARCHAR(80) NOT NULL,
  `actividad_secundaria` VARCHAR(80) NULL,
  `oper_compras` VARCHAR(100) NOT NULL,
  `oper_ventas` VARCHAR(100) NOT NULL,
  `inicio_actividad` DATE NULL,
  `ingresos_brutos` VARCHAR(45) NULL,
  `establecimiento_n` INT NULL,
  `n_libro_compras` VARCHAR(45) NULL,
  `n_libro_ventas` VARCHAR(45) NULL,
  `sede_timbrado` VARCHAR(45) NULL,
  `hoja_libro_compras` VARCHAR(45) NULL,
  `hoja_libro_ventas` VARCHAR(45) NULL,
  `activa` INT NOT NULL,
  `fecha_alta` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`idempresa`),
  UNIQUE INDEX `empresa_unica` (`idempresa` ASC),
  UNIQUE INDEX `cuit_unico` (`cuit` ASC))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `periodos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `periodos` ;

CREATE TABLE IF NOT EXISTS `periodos` (
  `idperiodo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `anio` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `activo` INT NOT NULL,
  `estado` VARCHAR(30) NOT NULL,
  `fecha_cierre` DATETIME NULL,
  `total_compras` FLOAT NULL,
  `total_iva_compras` FLOAT NULL,
  `total_ventas` FLOAT NULL,
  `total_iva_ventas` FLOAT NULL,
  `empresas_idempresa` INT NOT NULL,
  PRIMARY KEY (`idperiodo`, `empresas_idempresa`),
  UNIQUE INDEX `idperiodo` (`idperiodo` ASC),
  UNIQUE INDEX `pkperiodos`(`idperiodo`, `empresas_idempresa`),
  INDEX `fk_periodos_empresas1_idx` (`empresas_idempresa` ASC) VISIBLE,
  CONSTRAINT `fk_periodos_empresas1`
    FOREIGN KEY (`empresas_idempresa`)
    REFERENCES `empresas` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permisos` ;

CREATE TABLE IF NOT EXISTS `permisos` (
  `idpermiso` INT NOT NULL AUTO_INCREMENT,
  `permiso_sistema` JSON DEFAULT NULL,
  PRIMARY KEY (`idpermiso`),
  UNIQUE INDEX `idpermiso` (`idpermiso` ASC))
ENGINE = InnoDB
COMMENT = '	';

-- -----------------------------------------------------
-- Table `clave_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clave_token` ;

CREATE TABLE IF NOT EXISTS `clave_token` (
  `idclavetoken` INT NOT NULL AUTO_INCREMENT,
  `clave` VARCHAR(45) NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idclavetoken`),
  UNIQUE INDEX `pkclavetoken` (`idclavetoken` ASC))
ENGINE = InnoDB
COMMENT = '	';

-- -----------------------------------------------------
-- Table `personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `personas` ;

CREATE TABLE IF NOT EXISTS `personas` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `cuit` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(100) NULL,
  `localidad` VARCHAR(100) NULL,
  `codigo_postal` VARCHAR(20) NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `cuenta` VARCHAR(45) NULL,
  `n_ingr_brutos` VARCHAR(45) NULL,
  `cai` VARCHAR(45) NULL,
  `condicion_iva` VARCHAR(45) NOT NULL,
  `cliente_global` INT NOT NULL,  			-- Si vale 1 significa que todas las empresas
  `rubro_actividad` VARCHAR(45) NOT NULL,
  `fecha` DATETIME DEFAULT now() NOT NULL,
  `tipopersona` VARCHAR(20) NOT NULL,
  `empresas_idempresa` INT NULL,
  `usuarios_idusuario` INT NULL,
  `activo` INT NOT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `idxpersona_cuit` (`idpersona`, `empresas_idempresa`, `tipopersona`),
  UNIQUE INDEX `cuit_unico_personas` (`cuit` ASC),
   INDEX `fk_empresas_idempresa_per_idx` (`empresas_idempresa` ASC) VISIBLE,
  CONSTRAINT `fk_empresas_idempresa_per`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  INDEX `fk_personas_usuarios_idx` (`usuarios_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_personas_usuarios`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario_empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario_empresa` ;

CREATE TABLE IF NOT EXISTS `usuario_empresa` (
  `idusuario_empresa` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NULL,
  `nivel_permisos` INT NOT NULL,
  `usuarios_idusuario` INT NOT NULL,
  `empresas_idempresa` INT NOT NULL,
  PRIMARY KEY (`idusuario_empresa`, `usuarios_idusuario`, `empresas_idempresa`),
  UNIQUE INDEX `pkusuario_empresa` (`idusuario_empresa`, `usuarios_idusuario`, `empresas_idempresa`),
  UNIQUE INDEX `usuario_empresa` (`idusuario_empresa` ASC),
  INDEX `fk_usuario_empresa_usuarios_idx` (`usuarios_idusuario` ASC) VISIBLE,
  INDEX `fk_usuario_empresa_empresas1_idx` (`empresas_idempresa` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_empresa_usuarios`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_empresa_empresas1`
    FOREIGN KEY (`empresas_idempresa`)
    REFERENCES `empresas` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

CREATE TABLE IF NOT EXISTS `usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `en_sesion` INT NOT NULL,
  `fecha_alta` DATETIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `fecha_baja` DATETIME NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_unico` (`idusuario` ASC),
  UNIQUE INDEX `usuario_unico` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas` ;

CREATE TABLE IF NOT EXISTS `ventas` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `fecha_emision` VARCHAR(45) NOT NULL,
  `tipo_comprobante` VARCHAR(60) NOT NULL,
  `tipo_op_venta` VARCHAR(60) NOT NULL,
  `producto_servicio_cl` VARCHAR(45) NOT NULL,
  `n_comprobante` VARCHAR(10) NOT NULL,
  `letra_comprobante` VARCHAR(45) NULL,
  `n_cae` VARCHAR(45) NULL,
  `vencimiento_cae` VARCHAR(45) NULL,
  `total_venta` FLOAT NOT NULL,
  `tipo_moneda` VARCHAR(45) NOT NULL,
  `subtotal1` FLOAT NOT NULL,
  `neto_gravado1` FLOAT NULL,
  `iva1` FLOAT NOT NULL,
  `bandera_iva1` INT NOT NULL,
  `tipo_de_retencion` VARCHAR(60) NOT NULL,
  `producto_servicio1` VARCHAR(45) NULL,
  `fecha_de_pago1` VARCHAR(45) NOT NULL,
  `subtotal2` FLOAT NOT NULL,
  `neto_gravado2` FLOAT NULL,
  `iva2` FLOAT NULL,
  `bandera_iva2` INT NULL,
  `tipo_retencion2` VARCHAR(60) NULL,
  `producto_servicio2` VARCHAR(45) NULL,
  `total_retenciones` FLOAT NULL,
  `importe_exento` FLOAT NOT NULL,
  `importe_no_gravado` FLOAT NOT NULL,
  `impuestos_internos` FLOAT NOT NULL,
  `campo_auxiliar` FLOAT NULL,
  `diferencia_con_total` VARCHAR(45) NULL,
  `fecha` DATETIME NOT NULL,
  `empresas_idempresa` INT NOT NULL,
  `personas_idpersona` INT NOT NULL,
  PRIMARY KEY (`idventa`, `empresas_idempresa`, `personas_idpersona`),
  UNIQUE INDEX `pkventas` (`idventa`, `empresas_idempresa`, `personas_idpersona`),
  UNIQUE INDEX `ventas` (`idventa`),
  INDEX `fk_ventas_empresas1_idx` (`empresas_idempresa` ASC) VISIBLE,
  INDEX `fk_ventas_personas1_idx` (`personas_idpersona` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_empresas1`
    FOREIGN KEY (`empresas_idempresa`)
    REFERENCES `empresas` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_personas1`
    FOREIGN KEY (`personas_idpersona`)
    REFERENCES `personas` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `contabilidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contabilidad` ;

CREATE TABLE IF NOT EXISTS `contabilidad` (
  `idcontabilidad` INT NOT NULL AUTO_INCREMENT,
  `plan_de_cuentas` JSON NOT NULL,
  `empresas_idempresa` INT NOT NULL,
  PRIMARY KEY (`idcontabilidad`),
  UNIQUE INDEX `idcontabilidad` (`idcontabilidad` ASC),
  CONSTRAINT `fk_empresas2`
    FOREIGN KEY (`empresas_idempresa`)
    REFERENCES `empresas` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
